name: py-report
on:
  push:
  workflow_dispatch:
#  schedule:
#    - cron: "30 11 * * *"    #run at 11:30 UTC everyday
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3 
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest mypy pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        if: false
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Analysing the code with pylint
        if: false
        run: pylint $(git ls-files '*.py')
      - name: Analysing the code with mypy
        if: false
        run: mypy $(git ls-files '*.py')

      - name: execute py script
        run: python main.py
        env:
          RUNNER: ${{ github.repository_owner }}

      - name: Upload manifest result
        uses: actions/upload-artifact@v3
        with:
          name: py-rapport
          path: ./dist/*.txt
