name: readme
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3 
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest mypy pylint
          pip install jinja2
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Analysing the code with pylint
        if: false
        run: pylint $(git ls-files '*.py')
      - name: Analysing the code with mypy
        if: false
        run: mypy $(git ls-files '*.py')
      
      - name: execute py script
        run: python readme.py